# Site settings
title: 南×遊記
email: "huanghuangnz@gmail.com"
description: "奥特亚罗瓦的星空"
url: "https://huanghuangnz.github.io/"
baseurl: "/photo"
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   huanghuangnz
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://huanghuangnz.github.io/photo/gallery/"  
  - JOURNAL: "https://huanghuangnz.github.io/photo/journal/"
  - ABOUT: "https://huanghuangnz.github.io/photo/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

prose:
  rooturl: '_posts'
  siteurl: 'https://huanghuangnz.github.io/photo'
  media: 'assets/img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "img"
        field:
          element: "text"
          label: "img"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "wls"
              value: "微留学"
            - name: "blog"
              value: "见闻"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
